# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# For SEO, see: https://github.com/jekyll/jekyll-seo-tag
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
assetsurl: "/assets/images/"
social:
    instagram: https://instagram.com/callumflack
twitter:
    username: callumflack
google-analytics: UA-

# Defaults
defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            permalink: "/:categories/:title.html"
            layout: article

# Collections
collections:
    products:
        output: true

# Markdown settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

# Build settings
# Remove the CNAME if using Siteleaf!
exclude:
    - assets/_source
    - CNAME
    - Gemfile
    - Gemfile.lock
    - gulpfile.js
    - node_modules
    - package.json
    - README.md
    - TODO.md

# Plugin settings
gems:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
